language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - development
    - master
before_install:
- "sudo apt-get install rtorrent screen"
before_script:
- "psql -c 'create database cataract_test;' -U postgres"
- "cp config/database.yml{.travis,}"
- "mkdir -p tmp/sockets"
- "bundle exec rake db:migrate"
script: 
- "bundle exec rake cucumber:ok"
- "bundle exec rspec"
