language: ruby
rvm:
  - 2.2.0
branches:
  only:
    - development
    - master
    - /^feature\//
before_install:
  # Make sure /dev/shm has correct permissions. chrome has trouble running on openvz
  - ls -l /dev/shm
  - sudo chmod 1777 /dev/shm
  - ls -l /dev/shm
#  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo apt-get update -qq
#  - sudo dpkg -i ./google-chrome*.deb
  # install rtorrent from 14.04 trusty
  - mkdir -p debs/
  - wget -O debs/libtorrent.deb http://de.archive.ubuntu.com/ubuntu/pool/universe/libt/libtorrent/libtorrent14_0.13.2-1_amd64.deb
  - wget -O debs/rtorrent.deb http://de.archive.ubuntu.com/ubuntu/pool/universe/r/rtorrent/rtorrent_0.9.2-1_amd64.deb
  - wget -O debs/libsigc.deb http://de.archive.ubuntu.com/ubuntu/pool/main/libs/libsigc++-2.0/libsigc++-2.0-0c2a_2.2.10-0.2ubuntu2_amd64.deb
  - sudo dpkg -i debs/*
  - sudo apt-get -qq install screen chromium-browser mlocate redis-server
  - sudo apt-get -f install
  - sudo updatedb
  - createdb cataract_test
before_script:
  - "cp config/database.yml{.travis,}"
  - "mkdir -p tmp/sockets"
  - "bundle exec rake db:migrate"
  - "bundle exec rake assets:precompile"
  - "echo '--color --backtrace' > .rspec"
  - "cat /etc/redis/redis.conf"
  - "ps fax"
  - "netstat -atn"
#- "bundle exec chromedriver-update"
script:
  - bundle exec rspec
  - bundle exec cucumber -rfeatures features
after_failure:
  - cat log/capybara_test.log
  - cat log/rtorrent-test.log
services:
  - redis-server
