language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - development
    - master
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq install rtorrent screen chromium-browser mlocate
  - sudo updatedb
  - createdb cataract_test
before_script:
  - "cp config/database.yml{.travis,}"
  - "mkdir -p tmp/sockets"
  - "bundle exec rake db:migrate"
script: "bundle exec rspec && bundle exec rake cucumber:ok"
after_failure:
  - cat log/rtorrent-test.log
