language: ruby
rvm:
  - 1.9.3
branches:
  only:
    - development
    - master
before_install:
  - sudo aptitude -y install rtorrent screen chromium-browser
  - createdb cataract_test
before_script:
  - "cp config/database.yml{.travis,}"
  - "mkdir -p tmp/sockets"
  - "bundle exec rake db:migrate"
script: "bundle exec rspec && bundle exec rake cucumber:ok"
