#!/usr/bin/env ruby

ENV['PORT'] = '4567'

require 'rubygems'
require 'bundler'
Bundler.require :event_server
require 'json'

conns = []
DEBUG = true


Thread.abort_on_exception = DEBUG

get '/subscribe' do
  content_type 'text/event-stream'
  # FIXME INSECURE only allow from same domain
  headers['Access-Control-Allow-Origin'] = '*'
  stream(:keep_open) do |out|
    conns << out
    out.callback { conns.delete(out) }
  end
end

def maybe_delay(message)
  json = JSON.parse(message)
  if meta = json['_meta']
    if delay = meta['delay']
      sleep delay
    end
    json.delete('_meta')
    json.to_json
  else
    message
  end
end

def publish(io, channel, message)
  io << "event: #{channel}\n"
  io << "data: #{message}\n\n"
end

def debug(message=nil)
  if DEBUG
    $stderr.puts block_given?? yield : message
  end
end

Thread.new do
  redis = Redis.connect
  redis.psubscribe('message', 'message.*') do |on|
    on.pmessage do |match, channel, message|
      channel = channel.sub('message.', '')
      message = maybe_delay message


      conns.each do |out|
        publish out, channel, message
      end
    end
  end
end

run_transfer_publisher = true
Thread.new do
  while run_transfer_publisher
    if conns.length > 0
      json = [
        { id: 'AE596A610B269617E9163E69F82AFDACE20324DD', up_rate: rand(10000), down_rate: rand(50000), progress: rand(99) }
      ].to_json

      conns.each do |out|
        publish out, 'transfers', json
      end
    end

    sleep 1
  end
end
