#!/usr/bin/env ruby

ENV['PORT'] = '4567'

require 'rubygems'
require 'bundler'
Bundler.require :event_server
require 'json'

conns = []

get '/subscribe' do
  content_type 'text/event-stream'
  # FIXME INSECURE only allow from same domain
  headers['Access-Control-Allow-Origin'] = '*'
  stream(:keep_open) do |out|
    conns << out
    out.callback { conns.delete(out) }
  end
end

Thread.new do
  redis = Redis.connect
  redis.psubscribe('message', 'message.*') do |on|
    on.pmessage do |match, channel, message|
      channel = channel.sub('message.', '')

      json = JSON.parse(message)
      if meta = json['_meta']
        if delay = meta['delay']
          sleep delay
        end
        json.delete('_meta')
        message = json.to_json
      end

      conns.each do |out|
        out << "event: #{channel}\n"
        out << "data: #{message}\n\n"
      end
    end
  end
end
